### PR TITLE
Implement /list

### PR DESCRIPTION
**Pull request by maxpoulin64**
This re-adds @xPaw's `/list` implementation, with additional styling to make it look nice.

capture d ecran_2016-04-16_08-33-26

### CODE REVIEW

**Comment by xPaw** [comment]
:+1: 

Just wondering, will our tab complete "Channel list" due to #64?

**Comment by xPaw** [comment]
I've added `do not merge` label on this PR for now. Ideally we need some list safe guards in irc-fw for this to work nicely.

**Comment by maxpoulin64** [comment]
@xPaw: I just made a [PR in irc-framework](https://github.com/kiwiirc/irc-framework/pull/48) fixing the crash, and added a few safeguards on our end as well to avoid issues.

Turns out the W3C's IRC server violates the IRC standards... Because clearly, they're very good at dealing with standards.

**Comment by xPaw** [comment]
@maxpoulin64 irc-fw PR merged, could you rebase this?

**Comment by maxpoulin64** [comment]
@xPaw rebased

**Comment by MaxLeiter** [comment]
Bump?

**Comment by maxpoulin64** [comment]
@astorije: just rebased again. This one should be ready to be merged since major bugs have been fixed in irc-fw.

**Comment by astorije** [comment]
Somehow I was picturing this as a `do not merge`, not sure why. I'll play with it ASAP :-)

**Comment by MaxLeiter** [comment]
Testing this - do we want 'Loading channel list, this can take a moment...' to stay at the top of the channel buffer once its loaded? (example visible in first screenshot)

**Comment by astorije** [comment]
> Testing this - do we want 'Loading channel list, this can take a moment...' to stay at the top of the channel buffer once its loaded?

I'm in favor of removing it from the buffer after loading, if (easily) possible.

**Comment by MaxLeiter** [comment]
I think my comment above can be addressed in another PR; I think this is fine to merge

**Pull request merged**
