### PR TITLE
Change more to use id rather than count.

### PR DESCRIPTION
**Pull request by YaManicKill**
This needs to be merged before #759 

I haven't managed to 100% test it because I restarted the server just now and don't have any "more" to do. I'll test it once it has backed up a bit.

### CODE REVIEW

**Comment by astorije** [comment]
Just curious, what happens in channels that have a ton of join/parts but very few messages, like `#freenode`? Does it load potentially thousands of messages to try and grab 100 actual messages sent by people?

I get that your condensing PR would be solving that anyway, I'm just going over what happens/would happen in the interim.

**Comment by YaManicKill** [comment]
> Just curious, what happens in channels that have a ton of join/parts but very few messages, like #freenode? Does it load potentially thousands of messages to try and grab 100 actual messages sent by people?

This PR doesn't change this at all. It still gets 100 messages.

All it does is send the last message id, rather than the number of messages we currently have in chat window.

**Comment by YaManicKill** [comment]
Thanks, @xPaw, can confirm after I left it on all day that it works. Good stuff.

**Comment by astorije** [comment]
Thanks for the clarification, @YaManicKill!

**Pull request merged**
