### PR TITLE
Display unhandled numerics on the client

### PR DESCRIPTION
**Pull request by xPaw**

### CODE REVIEW

**Comment by xPaw** [comment]
Ready after #449

**Comment by astorije** [comment]
Reposting here after commenting on the wrong PR. Wow.

---

This is a nice addition, thanks!

One comment I have is: couldn't we wrap this behind a user setting, similar to the MOTD one? Not sure what name we could give it, but if it's a generic info checkbox, I would also put the "Enabled capabilities" there (if possible, of course).

Also (unrelated to this PR, but displayed by it), I noticed a line saying `[403] Freenode No such channel`, are we trying to join the lobby somewhere when first connecting?

**Comment by xPaw** [comment]
@astorije I don't think a setting for messages shown in server window is worth it.

**Comment by astorije** [comment]
Well, we'll have to deal with server window at some point still, because after this PR, we'll display everything or everything but the MOTD, which is the most human-readable information there lol.
But another fight, another day.

👍 and merging.

**Comment by astorije** [comment]
Damn, I just realized this wasn't in `second review needed`, sorry 😕
@maxpoulin64, @YaManicKill, are you 👍 on this *a posteriori* or do you want me to revert?

**Comment by maxpoulin64** [comment]
@astorije: fine by me, :+1:

**Pull request merged**
