### PR TITLE
Promisify auth methods

### PR DESCRIPTION
**Pull request by metsjeesus**
To make the flow clearer.  Have not tested LDAP login, but it should be same as old one.

### CODE REVIEW

**Comment by astorije** [comment]
@metsjeesus, could you rebase this on master please? You should see some CI failures around linting after that (same with #1235).

**Comment by metsjeesus** [comment]
I feel ive done something wrong. Git and github is hard.

**Comment by astorije** [comment]
Ouch, yes :/
So, the steps are as follows:

- You first need to sync _your_ `master` and _our_ `master`
  - On your working copy, first make sure you have a reference to our repo (but I am pretty sure you have it already with the following): `git remote add upstream https://github.com/thelounge/lounge`
  - Fetch our latest changes: `git fetch upstream`
  - Go to your `master` and sync ours onto it: `git checkout master && git rebase upstream/master`

- Now you need to rebase the synced up `master` onto your own branch: `git checkout metsjeesus/promisify-auth && git rebase master`

After that, you need to force push to your repo so this PR gets updated. There are multiple ways to do that, but this one _should_ fix your commit entanglement above.

**Comment by metsjeesus** [comment]
I probably do something differently.

- My working copy is cloned from lounge repository `git clone https://github.com/thelounge/lounge.git`. So origin will be thelounge repo.

- I add my repo `git remote add metsjeesus https://github.com/metsjeesus/lounge.git`

- I checkout base branch `git checkout xpaw/safer-auth-flow`

- I generate new branch `git checkout -b metsjeesus/promisify-auth`

- After code is added, push it to my github repo `git push metsjeesus metsjeesus/promisify-auth --force`

What i think the problem is, I dont use `master` as base branch, what means `./node_modules/.bin/eslint . --fix` fixes and commits all the eslint changes what `xpaw/safer-auth-flow` dont have.

**Comment by xPaw** [comment]
Closing for the same reason as in https://github.com/thelounge/lounge/pull/1235#issuecomment-314083457

**Pull request closed without merging**
