### PR TITLE
Add fix for undefined name being slugified

### PR DESCRIPTION
**Pull request by YaManicKill**

### CODE REVIEW

**Comment by xPaw** [comment]
I would rather figure out why its undefined.

**Comment by YaManicKill** [comment]
So, it comes from this slugify:

```
{{#each networks}}
<section id="network-{{id}}" class="network name-{{slugify name}} network-{{slugify serverOptions.NETWORK}}" data-id="{{id}}" data-nick="{{nick}}" data-options="{{tojson serverOptions}}">
	{{> chan}}
</section>
{{/each}}
```

Because the serverOptions.NETWORK is undefined, which is something we get from the server itself, connection.js:134:

```
network.serverOptions.NETWORK = data.options.NETWORK;
```

So, we could make some assumptions if we want, but it sounds like the server is just being stupid. This is snoonet server, btw.

**Comment by YaManicKill** [comment]
Actually, I guess we could use the name rather than serverOptions.NETWORK as that's user-defined, and means that if someone connects to the same server twice, the 2 slugs can have different names if the user wants them to, whereas this wouldn't be possible to do that. Also, means that we know it won't be undefined as it's required.

**Comment by astorije** [comment]
@xPaw, would it be reasonable to merge this until finding a proper fix? I'm in @YaManicKill's case right now: crash on startup, instance unusable without this.

**Comment by YaManicKill** [comment]
Based on what we know, I think this is an acceptable temporary fix (obviously I wrote it) as I feel we could easily bikeshed about the best way to solve it otherwise, but we can open another one to decide the best way to deal with it. But as of just now, master is broken for many people. 

@astorije What server is yours failing on? I bet this isn't a massively common thing as 3/4 of my servers send the string back, it's just the 1 that doesn't, and that's snoonet.

**Comment by xPaw** [comment]
What about adding `|| ""` network name? Or before calling slug in template, check if there is a network name. `name-` is kind of useless as is anyway. I really hate masking bugs like this PR currently does.

**Comment by YaManicKill** [comment]
> What about adding || "" network name?

What do you mean?

> Or before calling slug in template, check if there is a network name.

That could work.

> I really hate masking bugs like this PR currently does.

I don't think we are masking a bug, I believe this **is** a bug. I think we should also do something else, but this caused crashes because we didn't check that we have something that isn't undefined, that's the problem.

There are other problems as well, but this is still an issue.

**Comment by xPaw** [comment]
Just add an `if` around the slugify call then.

**Comment by YaManicKill** [comment]
> Just add an if around the slugify call then.

No, but if we have other places we use this, they will crash if we don't have this fix anyway.

**Comment by xPaw** [comment]
Other places slugify unknown commands and channel names, if these were to be unknown, i would rather get a bug report.

**Comment by YaManicKill** [comment]
> Other places slugify unknown commands and channel names, if these were to be unknown, i would rather get a bug report.

But this is not a good way to deal with this because it completely shuts down whatever we were trying to do. If we want to know about these things we shouldn't just let it all fail with an error on trying to call something from undefined.

**Comment by xPaw** [comment]
These shouldn't fail.

**Comment by YaManicKill** [comment]
Aight, have your "proper" fix. I hope you are happy.

**Comment by YaManicKill** [comment]
Merging as it's a small fix. @astorije will be happy to wake up to this.

**Pull request merged**
