### PR TITLE
One line server startup errors

### PR DESCRIPTION
**Pull request by xPaw**
Fixes this:

### CODE REVIEW

**Comment by astorije** [comment]
Hey @xPaw, could you post an "after" screenshot for this error? Curious what it'd look like.

**Comment by xPaw** [comment]
`timestamp [ERROR] Error: listen EADDRINUSE :::9000`

**Comment by astorije** [comment]
Does this correctly kill process when such error happens though?

**Comment by xPaw** [comment]
It dies on its own, yes. The only thing keeping the server running is `server.listen`, so if that fails it just quits.

**Comment by astorije** [comment]
Sounds good!

**Pull request merged**
