### PR TITLE
Display whitespace properly

### PR DESCRIPTION
**Pull request by maxpoulin64**
Fixes alignment in many server's motd as well as in-channel ASCII art

## Before
before

## After
after

### CODE REVIEW

**Comment by astorije** [comment]
Yes!! Thanks for that!!
I'll try some edge cases before giving my approval though.

**Comment by maxpoulin64** [comment]
@astorije Just fixed a bug with action messages. I think we should be covered now.

**Comment by xPaw** [comment]
Why not set it on `#chat .msg .text`?

**Comment by maxpoulin64** [comment]
@xPaw because it would break the other action templates due to extra whitespace. I had to edit `msg.tpl` and `msg_action.tpl` to glue the text right on the span, otherwise the extra tabs/spaces before and after would be displayed as well, making a mess. So I targetted those and only those to avoid bad surprises and WTF with the action templates.

**Comment by xPaw** [comment]
Ah yes, good point. Have you tested if super long/unicode lines overflow correctly with this patch?

**Comment by maxpoulin64** [comment]
It should be no different than before, since it's `pre-wrap` and not just `pre`. It should only affect tabs and space, but I admit I haven't tested that case. I can check a bit later if you want.

**Comment by xPaw** [comment]
I'm just wondering if it's going to conflict with `word-wrap: break-word;` we have on `.msg` or not.

**Comment by xPaw** [comment]
Unrelated note, can we get a `overflow: hidden` in that same selector? So that zalgo text and other crap doesn't overflow onto other lines.

**Comment by maxpoulin64** [comment]
@xPaw makes sense, updated.

**Comment by astorije** [comment]
Good job, guys! :+1:

**Pull request merged**
