### PR TITLE
Fix sending messages starting with a space

### LINKED ISSUE #319: Starting with " /" (whitespace + slash) does not send the message
This was fixed in a previous PR (~~https://github.com/thelounge/lounge/pull/154 I believe~~ Actually, I'm not sure we ever fixed this...) to allow escaping commands with a slash (`// something...`) or a leading whitespace (` /something...`).

### PR DESCRIPTION
**Pull request by maxpoulin64**
There really is no need to trim apart bringing more situations like this. If I want to put spaces in front of my message (say, for alignment purposes), then I should be able to.

Fixes #319

### CODE REVIEW

**Comment by xPaw** [comment]
Not trimming is fine, however I think we should block empty messages (e.g. spaces only).

**Comment by YaManicKill** [comment]
> Not trimming is fine, however I think we should block empty messages (e.g. spaces only).

Agreed, we don't want to send empty messages.

**Comment by astorije** [comment]
@maxpoulin64, any chance you could address the comments above? (Removing the `second review needed` label until then)

**Comment by xPaw** [comment]
As someone pointed out in irc, people might want to send empty messages (even if that's silly). Also checked HexChat, they allow it too.

So I'll be fine with this fix.

**Comment by astorije** [comment]
👍

**Pull request merged**
