### PR TITLE
Correctly show whitespace and newlines in messages

### PR DESCRIPTION
**Pull request by starquake**
Screwed up last PR so here's a clean one. Fix for https://github.com/thelounge/lounge/issues/1229

Extension of https://github.com/thelounge/lounge/pull/1237

### CODE REVIEW

**Comment by starquake** [comment]
Fixing the lint issues...

**Comment by YaManicKill** [comment]
I'll review this tomorrow.

**Comment by xPaw** [comment]
So I don't think it's worth the trouble to apply `white-space` on every message type. Just `notice`, `motd` and `message` would be enough I think. Then modifying templates for different actions wouldn't be required.

**Comment by starquake** [comment]
But... how about some one doing:`/kick You got kicked =>  L  O  L  <=` or `/quit some    fancy   quit 
  message   with   spaces`

**Comment by xPaw** [comment]
@starquake Quit message has `quit-reason` class for example, could apply on it. I just think applying on `.text` as a generic will always bring us problems with whitespace in templates.

**Comment by starquake** [comment]
Mmmm yeah maybe we should. I see ctcpMessage has no class though. Is it okay to add one there? Any suggestions for a name?

**Comment by xPaw** [comment]
Yes, we can safely add classnames on all the stuff that has parsed messages. `ctcp` would be it's own action and can be matched like '.msg.ctcp .text`.

**Comment by starquake** [comment]
There's a newline in the .ctcp .text so this will become visible. Here's the ctcp template:
```
{{> ../user_name nick=from}}
<b>{{ctcpType}}</b> {{{parse ctcpMessage}}}
```
Do you want me to:

1.  change the template
2. add a class in the template

**Comment by xPaw** [comment]
Wrapping ctcpMessage in a span should be good.

**Pull request merged**
