### PR TITLE
The Lounge Awakens

### PR DESCRIPTION
**Pull request by astorije**

### CODE REVIEW

**Comment by xPaw** [comment]
Why did you remove `.travis.yml`?

**Comment by astorije** [comment]
@xPaw, commit message is:

> Remove Travis CI configuration for now …
> Pretty much the entire file is invalid now and Travis CI has not been enabled here yet.

Out of the previous file:
- Node versions is not up-to-date anymore (I wanted to remove 0.10 but maybe not a good idea since Jessie is running it)
- `sudo: false` is not necessary anymore
- The `deploy` section is now invalid

On top of that, since we had only 1 test (lol), Travis CI is merely used to deploy on npm. I will re-add an updated Travis file before the end of the week and before the npm package gets published, now I was merely removing all references to "shout" itself.

Hope that helps :)

**Comment by xPaw** [comment]
> On top of that, since we had only 1 test (lol), Travis CI is merely used to deploy on npm.

It also ran eslint.

**Comment by astorije** [comment]
Correct, forgot about that. But don't worry, it's a temporary removal until I enable Travis CI.

**Pull request merged**
