### PR TITLE
Prototype of server-side message search

### PR DESCRIPTION
**Pull request by xPaw**
MVP. Gib feedback. This kinda abuses the channel model.

### CODE REVIEW

**Comment by metsjeesus** [comment]
Limit result size, add time, network and channel as parameter.

**Comment by xPaw** [comment]
I do want to add search settings:
- Scope:
 - All
 - Network
 - Channel

- Case-sensitive

But that's to be done after the `prompt` is removed in favor of a proper UI design.

**Comment by astorije** [comment]
In terms of scope or settings, we could use something àla GitHub prefixes: https://help.github.com/articles/searching-repositories/

I understand you are searching among the messages already in memory, correct? Why not search in logs (when available) instead?
That would provide more history to search in, and would decouple from in-memory stuff, which ideally we should not be relying upon for historical content.

**Comment by xPaw** [comment]
> In terms of scope or settings, we could use something àla GitHub prefixes:

I'd want UI for it too.

> I understand you are searching among the messages already in memory, correct? Why not search in logs (when available) instead?

I would wait to get some kind of logging abstraction api for that first. Do not want to mess with parsing log files at the moment.

**Comment by astorije** [comment]
> Do not want to mess with parsing log files at the moment.

Meh, it's not that bad #663 😄

**Comment by YaManicKill** [comment]
What's the status of this?

**Comment by xPaw** [comment]
Needs UI work.

**Comment by xPaw** [comment]
Rebased on master, a little bit more simpler code (currently pretends to be a query window).

**Comment by astorije** [comment]
I am very puzzled right now:

screen shot 2017-07-21 at 02 50 14

**Pull request closed without merging**
