### PR TITLE
Fix #116: Move 'you' handling in invites to the client

### LINKED ISSUE #116: Clickable "you" when being invited
When another user invites the current user to a channel, the following statement is being shown to the current user:

> **astorije** invited **you** to #astorije

However, **you** is clickable, while it should not.

Looks like this in practice:

screen shot 2016-02-27 at 19 22 03

### PR DESCRIPTION
**Pull request by xPaw**

### CODE REVIEW

**Comment by astorije** [comment]
@xPaw, does the client have a reference to the user's nick? If so, we could have the equality check in the template directly rather than passing that `invitedYou` in the event. If not, nevermind then.

**Comment by astorije** [comment]
Marking with `priority` label here: it's a regression compared to the latest release, `v1.2.1`, so let's not ship that in the next release.

**Comment by maxpoulin64** [comment]
:+1:

**Comment by astorije** [comment]
Will +1 and merge when @xPaw addresses (or not) my comment above :-)

**Comment by xPaw** [comment]
It does not have a reference.

**Pull request merged**
