### PR TITLE
Handle `CHGHOST` cap

### PR DESCRIPTION
**Pull request by xPaw**
This needs testing on a network that supports it.

### CODE REVIEW

**Comment by MaxLeiter** [comment]
Testing on `testnet.inspircd.org` by changing my mode to `+x` on one client and watching with another.

Don't currently have time to debug but the host being changed isn't reported at all.

**Comment by xPaw** [comment]
@MaxLeiter https://github.com/kiwiirc/irc-framework/commit/c725576be81c9b32c394ded5ea3fc25d4a02cd26 this?

**Comment by xPaw** [comment]
I just tested it with the fix applied, it shows the new hostname correctly.

**Comment by MaxLeiter** [comment]
Works for me with fix applied, but is this really something we want users to see? I think `CHGHOST` is more useful for state management (i.e. updating `user` objects), not necessarily for notifying users.

**Comment by astorije** [comment]
Still a do not merge, @xPaw?

**Comment by xPaw** [comment]
@astorije Needs a irc-fw update

**Comment by astorije** [comment]
@xPaw, now that `irc-framework` has been bumped, does this need changes before we can merge?

**Comment by astorije** [comment]
Also, should this be added to the IRCv3 GitHub project? (I believe that would be https://github.com/thelounge/lounge/projects/1#card-242870)

**Comment by astorije** [comment]
Rebased on `master` and fixed ESLint issue.

**Pull request merged**
