### PR TITLE
Allow shout-irc to be proxied behind a /path/ url

### PR DESCRIPTION
**Pull request by gdamjan**
contains three small changes to use relative urls instead of absolute rooted at /
* favicons in index.html
* badge and pop sound in shout.js
* the url for the socket.io endpoint

### CODE REVIEW

**Comment by wizardfrag** [comment]
LGTM :+1:

**Comment by FryDay** [comment]
Might be petty, but you may want to change your commit message from shout-irc to lounge to avoid any confusion.

**Comment by xPaw** [comment]
:+1:

**Comment by YaManicKill** [comment]
:+1:

**Comment by astorije** [comment]
Merged in #20 with reworded commit message (but you still are credited in the contributors and you'll be part of the changelog :p).
Thanks a lot @gdamjan, great feature!!

**Pull request closed without merging**
