### PR TITLE
Update depdencides to latest stable versions

### LINKED ISSUE #740: High severity vulnerability affecting this repo
Hi there, 

We noticed that your repo has a high severity vulnerability: 
* [Regular Expression Denial of Service](https://snyk.io/vuln/npm:negotiator:20160616?utm_source=gh_issue)
* Affected package: negotiator<= 0.6.0

[Here is the test report for this repo](https://snyk.io/test/github/thelounge/lounge?utm_source=gh_issue). 
If you’d like to fix this vulnerability, Snyk lets you generate a pull request that recommends the best upgrade path - there’s a link to fix this vulnerability on the test report. 

Stay secure :-)

Ben from the Snyk team

### PR DESCRIPTION
**Pull request by xPaw**
Closes #740 too.

Minor version changes in these packages had perf improvements, bug fixes and dropped support for node <4.

### CODE REVIEW

**Comment by xPaw** [comment]
Removing appveyor cache fixed the issue 🤷

**Comment by astorije** [comment]
lol, this makes no kind of sense unless their caching system is properly broken. Also, one of the builds is still broken. Let's wait and see what their support say (if they answer this week) otherwise I'll be ok removing the cache if we can have both builds passing.

**Comment by xPaw** [comment]
Try to restart the build, should fix it self.

**Comment by astorije** [comment]
Tried that twice, still failing. What a pain AppVeyor can be...

**Comment by astorije** [comment]
My bad, another re-build fixed it. Whatever.
I'm good with this, AppVeyor has been a pain all along and builds are not even faster.

**Pull request merged**
