### PR TITLE
Simplify text input form

### PR DESCRIPTION
**Pull request by xPaw**
Removes the double wrapping we had. Tell me if it's better or worse.

29-2048-2b03670

### CODE REVIEW

**Comment by JustRamon** [comment]
Better IMO

**Comment by astorije** [comment]
Same comment as #359, the current one fits very well in the theme. I'd be more in favor of a new "flat-UI" theme that matches your preference.

**Comment by williamboman** [comment]
The placeholder color in Zenburn is a little hard to read, possibly add;

```diff
diff --git a/client/themes/zenburn.css b/client/themes/zenburn.css
index fd13d55..275efa7 100644
--- a/client/themes/zenburn.css
+++ b/client/themes/zenburn.css
@@ -183,6 +183,10 @@ body {
 	color: #dcdccc;
 }
 
+#form #input:-ms-input-placeholder { color: #a1a197; }
+#form #input::-moz-placeholder { color: #a1a197; }
+#form #input::-webkit-input-placeholder { color: #a1a197; }
+
 /* Buttons */
 #chat .show-more-button {
 	background: #434443;

```


screenshot 2016-05-30 at 18 20 28

**Comment by dgw** [comment]
Those selectors should be comma-separated so as not to duplicate the `color` property, but I agree with changing that color.

**Comment by williamboman** [comment]
> Those selectors should be comma-separated so as not to duplicate the color property, but I agree with changing that color.

Not possible due to vendor incompatible pseudo-selectors (in accordance with the CSS spec).

**Comment by dgw** [comment]
Surprising that the spec doesn't allow for ignoring only elements of comma-separated selectors, since each list item is independent of the others, but so be it; the W3C hath spoken.

**Comment by YaManicKill** [comment]
@astorije Are you against this going in as-is and want a new theme instead? Personally, I think it works fine in the theme, but if you are very against it, then we should probably not leave it hanging around.

**Comment by astorije** [comment]
@YaManicKill, if everyone is in favor, then I'll go with the flow :-) I'll review/test it ASAP.

**Comment by maxpoulin64** [comment]
Alright, since people seems to like it, this is a 👍 for me. It will also make #379 look a bit better, as right now the box is bottom centered and it's a bit weird looking.

capture d ecran_2016-07-01_20-18-42

capture d ecran_2016-07-01_20-32-52

**Comment by xPaw** [comment]
@maxpoulin64 will have to be rebased after your PR is merged, but yea.

**Comment by williamboman** [comment]
Nooo what happened here?

**Pull request closed without merging**
