### PR TITLE
Make whois a client template

### PR DESCRIPTION
**Pull request by xPaw**
chrome_2016-03-07_17-10-29

Supercedes #129

### CODE REVIEW

**Comment by astorije** [comment]
Nice @xPaw, it's looking good!
One minor suggestion, could we have channels displayed as `is on the following channels: #channel1, #channel2, and #channel3`?
It would look even more user-friendly :-)

**Comment by maxpoulin64** [comment]
I like that, much better looking and better handled. :+1:

**Comment by xPaw** [comment]
@astorije That's slightly tricky because it uses `each` loop in the template.

**Comment by astorije** [comment]
We could either use tricks to deal with that in the template, but yes, not pretty. A better way would be to define a human-readable list helper (along those lines: http://stackoverflow.com/a/18831911/1935861) but definitely not worth holding off this PR. I'll make an additional PR later for this :-)
:+1:

**Pull request merged**
