### PR TITLE
Add support for hexip ilines and fix storing client ip in config

### PR DESCRIPTION
**Pull request by xPaw**
cc @MaxLeiter. This is mostly for demo purposes.

- Fixes saving ip and hostmask in user config
- Force user config save when connecting to a network
- Update old existing networks to have ip/hostmask on socket attachment

### CODE REVIEW

**Comment by maxpoulin64** [comment]
Hmm, the user's IP actually is stored on disk, or at least it is when webirc is enabled. Maybe we could recycle that for the hex ident?

Maybe we could even make the config option support passing in a function so people can customize it to whatever non-standard their servers need?

**Comment by xPaw** [comment]
@maxpoulin64 Yeah I saw the webirc code for that, it was a little suspect, but probably can just always store ip/hostmask in the config.

As for the function, do you know servers that support other methods? Might not be worth the investment.

**Comment by xPaw** [comment]
This PR should hide the username field on the client if the option is enabled.

**Comment by stepie22** [comment]
I believe this would address issue #374 ?

**Comment by astorije** [comment]
> This is mostly for demo purposes.

Just curious, is this something we want to include with the codebase we release then?

If yes, how ready is this?

**Comment by xPaw** [comment]
Should be ready.

**Pull request merged**
