### PR TITLE
Link to lounge demo from irc badge

### PR DESCRIPTION
**Pull request by Henni**
Just a small change for the README

### CODE REVIEW

**Comment by MaxLeiter** [comment]
Might be bias, but :+1: from me. Not everyone looks at the website.

**Comment by YaManicKill** [comment]
Yeah, I don't see why not, the demo puts people into #thelounge doesn't it? 2 birds, 1 stone.

**Comment by maxpoulin64** [comment]
Yeah sounds good to me too, :+1:

**Comment by astorije** [comment]
One of the reasons why we couldn't do that on https://github.com/erming/shout was that the demo is connecting to a test IRC server and locked to it. We'll probably want to do that as we attract more users, but in the meantime, this is good enough: :+1:.

@MaxLeiter, do you mind locking the demo to Freenode, then?

**Comment by MaxLeiter** [comment]
It already is, @astorije (thanks to @xPaw for implementing locking networks)

**Comment by astorije** [comment]
My bad, I didn't realize it was the case on the demo!

**Pull request merged**
