### PR TITLE
Fix sidebar channel drag'n'drop (#494)

### PR DESCRIPTION
**Pull request by metsjeesus**
Added 1 pixel snap to bottom, seems to fix the problem

### CODE REVIEW

**Comment by MaxLeiter** [comment]
Please update your commit to say "fixes #494" or something similar so GitHub realizes you're referencing an issue

**Comment by maxpoulin64** [comment]
I will have to review this later to make sure it works consistently. Thanks for the fix!

In the meantime, can you please squash the two commits together? Also please try to make a more descriptive title. I suggest putting the "Fixes #494" on a second line in the commit, [like this](https://github.com/thelounge/lounge/commit/4336699b494b27ce45bdb89a74d9a558a8d66851).

**Comment by metsjeesus** [comment]
What i should do to squash them? Where i can find the place?

**Comment by maxpoulin64** [comment]
@metsjeesus: Just run `git rebase -i HEAD^^` while on the branch, and set the second one to be squashed. Then you `git push -f` to update the PR.

**Comment by metsjeesus** [comment]
@maxpoulin64 I edited code in this github editor.  Im not home in this git and version managment system. Sorry, but i have no idea how to do that.

**Comment by astorije** [comment]
Hey @metsjeesus, how did you test that this was fixing it? I gave it a quick try and the bug is still there with your PR.
I also don't see how [`cursorAt`](https://api.jqueryui.com/sortable/#option-cursorAt) would specifically fix it, but I'm unclear on that option anyway.

**Comment by metsjeesus** [comment]
Tested on chrome with windows 10.  I could replicate bug consistently when i grabbed bottom side of the area while grabbing top side was clean. https://api.jqueryui.com/draggable/#option-cursorAt

**Comment by astorije** [comment]
I have just tried again and can confirm that bug is still there with this PR.
@metsjeesus, are you willing to do some more research on this?

I'm going to close this PR as `invalid` so any other work/discussion on this starts fresh and can link to that current thread.
Sorry about that, but nice try 😅

**Pull request closed without merging**
