### PR TITLE
Prevent overwriting username if manually typed by user (Fixes #843)

### LINKED ISSUE #843: Filling in username and then nick will override username
This piece of code produces very poor UX. https://github.com/thelounge/lounge/blob/6466680a8efc2f18608ae0204b027cbff60048cf/client/js/lounge.js#L1279-L1282

### PR DESCRIPTION
**Pull request by pallavagarwal07**
I know this was already being done in Pull #873, but this one is a simpler solution (and that pull request seems to be stalled for a month now)

### CODE REVIEW

**Comment by xPaw** [comment]
The form is global and state is kept even after you close it or connect to a new server, so this would disable it completely until a page reload.

**Comment by pallavagarwal07** [comment]
@xPaw I thought that was desired. Does this look better (submission of form will reset state)?

**Comment by xPaw** [comment]
I'm more inclined towards #873 fix.

**Comment by pallavagarwal07** [comment]
@xPaw #873 seems to have unwanted behaviour. If I type username first, and then nickname, but username is a prefix of nick.

Demo (from #873):
ev

**Comment by xPaw** [comment]
^ cc @PolarizedIons

**Comment by astorije** [comment]
@pallavagarwal07, I am closing this as we merged #873, but thanks a lot for your effort and contribution, I hope you'll help us again in the future :)

> @xPaw #873 seems to have unwanted behaviour. If I type username first, and then nickname, but username is a prefix of nick.

I am just seeing this after merging #873 though, sorry! @pallavagarwal07 and @PolarizedIons, could you guys maybe help by working together on a fix? That would be very much appreciated! 😊

**Pull request closed without merging**
