### PR TITLE
Add a shrug command

### PR DESCRIPTION
**Pull request by karbowiak**
Shruggie is great for when you just don't give a fuck..

Also moved parts of the me command to it's own function called handleMe, easier to reuse that way

### CODE REVIEW

**Comment by dgw** [comment]
Looks like `/slap` is leftover from the old Shout days, two years ago. To me, both `/slap` and `/shrug` belong in plugin territory. The Lounge will have a plugin/module system in the future (worked on in #77), and extra commands would be a great use case for plugins.

That said, if @thelounge/maintainers are OK having this in core until such time as plugins exist, I don't strenuously object. Any protocol-unrelated commands can be split out into plugins at that later date.

**Comment by MaxLeiter** [comment]
Agree with @dgw. As a note, @thelounge/maintainers should work.

**Comment by dgw** [comment]
@MaxLeiter Interesting. I put in @thelounge/maintainers and it didn't highlight.

**Comment by xPaw** [comment]
Yeah, there's no purpose to ship this. :-1: 

@dgw, @MaxLeiter Only members can mention teams.

**Comment by astorije** [comment]
This is clearly a cry for packages indeed.

On one end, we already have `/slap` so we could indeed take it until we split them apart. On the other end, accepting this is opening the door to all sorts of PRs to add people's crazy ideas :-)

So I would be 👎 as well, but I'd rather have @maxpoulin64 and @YaManicKill's opinion before closing this. Sorry @karbowiak and thanks for you contribution(s) still!

**Comment by YaManicKill** [comment]
Yeah, I'm agreed. 

I am obviously a bit torn, because we keep saying things would be good for plugins, but we still don't have any way to do plugins, but yeah I don't think this is good.

Similarly, I talked to @karbowiak on the irc and explained about text expanders which would allow him to do this easily anyway.

**Pull request closed without merging**
