### PR TITLE
Revert "Allow The Lounge to be proxied behind a /path/ url"

### PR DESCRIPTION
**Pull request by astorije**
Reverts thelounge/lounge#20

This PR breaks The Lounge: as `./socket.io/` cannot be found, the client restarts in loop many times per second.

@gdamjan, sorry for merging too soon, would you mind taking a look at this? Thanks!

### CODE REVIEW

**Comment by astorije** [comment]
Merging this revert as-is as `master` is currently broken...

**Comment by gdamjan** [comment]
socket.io is idiotic. I'll send a new pull request

**Comment by gdamjan** [comment]
OTOH. that hard `refresh()` on disconnect is not the best idea. at least it should have some backoff and possibility to debug.

**Comment by YaManicKill** [comment]
@gdamjan Yeah, I've got a branch on my fork to remove that because it's actually unneessary (socket io reconnects fine) but I'm testing it out irl for a while before merging it back.

**Comment by astorije** [comment]
Agreed @gdamjan and @YaManicKill, sorry I didn't investigate more to fix this, but first I wouldn't have merge without having a review if I had tried to fix the issue (while a revert is an emergency feature), and it was the middle of the night, I merely wanted to fix master.
I'm glad you reacted lightning fast though, thanks :-)

**Pull request merged**
