### PR TITLE
Fix themes not being found in theme selector dropdown, and being incorrectly served from the public folder

### LINKED ISSUE #1968: Built-in themes are not available anymore
I was giving one last test before releasing `v2.7.0-rc.1` and in the settings...

screen shot 2018-01-12 at 00 11 19

Built-in themes (Example, Morning, Zenburn, Crypto) do not show there. However, if I install a theme with `thelounge install`, it will correctly show in the dropdown.

No errors or warnings in the browser JS console, the server console, nor the Webpack output, which correctly contains the following:

```
               themes/crypto.css    1.55 kB          [emitted]
              themes/example.css  819 bytes          [emitted]
                   css/style.css      46 kB          [emitted]
              themes/morning.css    4.63 kB          [emitted]
               css/bootstrap.css    18.5 kB          [emitted]
              themes/zenburn.css       5 kB          [emitted]
```

We very recently merged https://github.com/thelounge/lounge/pull/1619 which touches themes, so that might be a good first place to look at.

### LINKED ISSUE #1969: "/themes/:theme.css" route is not actually used for local themes
This one cost me some hair to figure it out...

When going to, say `/themes/zenburn.css`, https://github.com/thelounge/lounge/blob/3eb017c/src/server.js#L51-L58 is not actually called. Instead, it directly loads the static file located at `public/themes/zenburn.css` due to the `.use(express.static("public"))` declaration a bit above.

What this means is that the `filename` value at https://github.com/thelounge/lounge/blob/3eb017c/src/plugins/packages/themes.js#L49 is actually never used. In fact, this value is currently broken (see #1968) but the built-in theme files are correctly found because that route never gets hit.

I'm not 100% sure what's the ideal fix for this: accept the current situation and not attempt to build the `filename` path for built-in (local) themes, or make sure local themes go through the same route than external ones.
I prefer the latter for consistency and avoid surprising of having 2 very similar URLs being handled differently (in fact, I couldn't find out why my `console.log`s were not being printed out and was wondering about cache). If the latter, then we should remove local themes from the `public` folder, since we now serve them through the server and not as static assets.

### PR DESCRIPTION
**Pull request by astorije**
Fixes #1968.
Fixes #1969.
Supersedes #1970.

This highlights an anti-pattern (that we might have in other places?): Building/Serving files located in the `public` folder means we're asking Express to serve files that are already publicly available, i.e. served. In this case, we're serving themes at `/themes/:theme.css` **and** files that live at `/public/themes/*.css` behind the same route.

So, since we're serving it via Express, we can remove it from the Webpack config.
Reason why I moved the files from the client to the server is because, in the end, that's where we serve them from. Installed themes with `thelounge install` actually have nothing to do with client code, they're much closer to server code, so this makes it more consistent. Additionally, if we were to keep themes in client folder, that means we'd have to load a file located at `../client` from the server, and I think we should avoid these server/client mixes.

I'm not too concerned about location of those themes anyway, because in the future I think we will move them to their own repos, npm packages, and have some or all being shipped/installed by default with TL.

### CODE REVIEW

**Comment by xPaw** [comment]
I really don't want to move themes into src folder like you did here. Reason public folder exists is.. precisely that, only files that are publicly accessible are within that folder.

I'd say go with #1970, because local themes need to be eventually turned into proper themes at some point anyway so the local theme functions you modified will go away.

**Comment by YaManicKill** [comment]
I'm with @xPaw on not moving them. Although, I should note that files from packages and themes aren't moved to public, because they can't if we don't want to have to require a build step. The server serves the files directly.

I feel like we should go with #1970 and just not copy the files to the public folder, and serve them the same was as we serve the packaged themes. Or we just keep the fact that they are stored in public, and just use that. Either way, yeah, I'm not a fan of this. Sure, they are served by the server, but they are client code, not server code.

**Comment by astorije** [comment]
> Reason public folder exists is.. precisely that, only files that are publicly accessible are within that folder.

Except themes that way aren't strictly publicly accessible, they're proxied by the server, like `index.html` (which isn't in the `public` folder) or installed themes.

> local themes need to be eventually turned into proper themes at some point anyway so the local theme functions you modified will go away.

👍
Agreed, hence my last paragraph in PR description.

---

Anyway, keeping this in the client folder means the server code will reference stuff in the client folder, which I hate. But oh well.

**Comment by astorije** [comment]
Reopened and updated #1970 accordingly.

**Pull request closed without merging**
