### PR TITLE
Do not match nicknames incorrectly as part of a bigger word

### LINKED ISSUE #1776: Nick detection in messages highlights some messages wrong
lucks test luck (luck is an user, it colors the first luck but not the second, should be the other way around). 
Usernames in actions don't seem to get colored at all.

I'll add more cases when I find them but most of the time when it highlighted it wrong was related to the first case.

### LINKED ISSUE #1885: Drop nickname length restriction for highlighting
Currently, highlighting works if nickname length is equal or more than 4, usernames shorter than the limit get ignored. The reported reason for this is that common words can clash with short nicknames such as the word `the`, which might be confusing to users. Thinking about it, the chance of a common word clashing with a short nickname seems similar to a common word clashing with a long nickname. Happy to do some statistics if anyone's interested, although think there shouldn't be a limit to the nickname highlighting functionality.

### PR DESCRIPTION
**Pull request by xPaw**
Fixes #1776
Fixes #1885

I tried really hard to inject indexes into the style parser as sent by the server but couldn't figure out a solution, so I did the same regex as the server (minus colors) to fix it instead.

### CODE REVIEW

**Comment by astorije** [comment]
@MaxLeiter, would you be able to review this?

**Comment by astorije** [comment]
@xPaw, is there any new or improved tests we could add for this?

**Comment by xPaw** [comment]
@astorije Added.

**Comment by astorije** [comment]
You rock 🎸

**Pull request merged**
