### PR TITLE
Fix how highlights are handled

### LINKED ISSUE #90: Actions containing Highlights display incorrectly
Actions have the sender's nickname to the right of the bar which separates nicknames and messages.

When an Action contains a Highlight, the action displays correctly except the nickname appears to the left of the aforementioned bar.

[Here's an example](http://i.imgur.com/8bs3M2Z.png)

([Here's an example from the other side, courtesy of IRC user vectr0n](https://vectr0n.net/img/uploads/big/ac443ec62b006ffc37a512d3dbd75dee.png))

This is likely a minor fix to move the name back across the bar. I would also encourage changing the color to the red highlight color. The placement of the nick and the star icon both clearly indicate that it's an Action, but nothing indicates that it's a Highlight except the sound and badge. I believe we would be better served by having Actions that contain Highlights appear red.

### PR DESCRIPTION
**Pull request by xPaw**
- Partially fixes #90 where highlighted actions were broken
- Sent actions are correctly identified as `self`
- Sent actions are correctly highlighted (previously this only worked when reloading from history)
- Minor performance improvement where received messages are no longer split twice

### CODE REVIEW

**Comment by maxpoulin64** [comment]
This one seems to break notifications on highlight. I put my test instance on a random channel and highlighted myself, but I didn't get the desktop notification and the badge didn't turn white either. It just displayed as if it was any other non-highlight channel message.

I also noticed the line doesn't get colored at all, so it's not clear it's a highlight. It just stays orange.

Did I miss something? I did run `npm run build` before and cleared the browser cache.

**Comment by xPaw** [comment]
Was there a .highlight class applied? Was it an  action?

**Comment by maxpoulin64** [comment]
Yes, the .highlight class gets applied properly. But with both actions and regular messages, no desktop notification gets received, and the badge doesn't turn white. With regular messages, the line does turn red as expected however.

```html
<div class="msg message highlight">
	<span class="time">
		03:49
	</span>
	<span class="from">
		<a href="#" class="user" style="color: #ff514d">Max-P_test</a>
	</span>
	<span class="text">
			Max-P: That still works
	</span>
</div>
```

```html
<div class="msg action highlight">
	<span class="time">
		03:48
	</span>
	<span class="from"></span>
	<span class="text">
		<a href="#" class="user">Max-P_test</a>
		
		 highlights Max-P
	</span>
</div>
```

Switching back to master, it all works again.

**Comment by xPaw** [comment]
This PR doesn't fix color on highlight (the other PR does), so that's fine. Unsure about notification though.

**Comment by maxpoulin64** [comment]
Found it: [highlight checked here](https://github.com/thelounge/lounge/blob/master/client/js/lounge.js#L655) and [broken here](https://github.com/xPaw/lounge/commit/24eb89cbc2e01654faaae7090fbb8e176ff63942#diff-1afea02ef01ba2e45ce6e3e55a2dbf82L39)

Since you're adding an `highlight` property it should be an easy fix actually.

**Comment by xPaw** [comment]
Template adds the highlight class though, so that  doesn't make sense.

**Comment by maxpoulin64** [comment]
It's not checking the class, it's checking the message type directly from the server event.

**Comment by xPaw** [comment]
Ah, my bad.

**Comment by xPaw** [comment]
@maxpoulin64 Should be fixed now.

**Comment by maxpoulin64** [comment]
I confirm it works fine for me now, :+1:

**Comment by astorije** [comment]
:+1:

**Pull request merged**
