### PR TITLE
Add common emoji shortcuts/ascii faces to emoji map

### PR DESCRIPTION
**Pull request by MaxLeiter**
Added some emoji shortcuts (:) -> 😃, :( ->🙁, etc).

One downside, and I'm not sure there's a fix which is probably a dealbreaker, is they're ugly when they show up in the autocomplete dropdown:

image

### CODE REVIEW

**Comment by astorije** [comment]
I don't know if this what this PR does exactly, but I personally hate when a client replaces ":)", ":(" with emoji. It used to be very fashionable some time ago, but much less so since the `:emoji:` syntax became a de facto standard.
And even clients who do that (well, those I know) either have an option to disable it, or it's disable by default.

**Comment by MaxLeiter** [comment]
astorije: it doesn't replace automatically, it acts the same as regular replacing. If the user hits enter on the emoji, it will change to emoji. Otherwise it will remain `:)` or whatever they type.

**Comment by YaManicKill** [comment]
Why did you close this, @MaxLeiter? I like the idea of it. My main question would be whether it should be :): or ::):

**Comment by MaxLeiter** [comment]
@YaManicKill - couldn't think of a nice UX

**Pull request closed without merging**
