### PR TITLE
Run any command when invalid password was entered

### PR DESCRIPTION
**Pull request by bews**
Very useful to detect and stop bruteforce attacks.

Related issue: #1048

### CODE REVIEW

**Comment by xPaw** [comment]
This looks like a security disaster.

**Comment by bews** [comment]
> This looks like a security disaster.

You're right, completely forgot about some things :sob: 
Check it now.

**Comment by astorije** [comment]
Shouldn't we be emitting auth logs like other tools (ssh, etc.) and then monitoring, fail2ban, others, rely on output of this, instead of running a command from our program?

**Comment by astorije** [comment]
I get the intent, but lots of these would be too much of a privacy
intrusion for The Lounge in my opinion.
Logging all abnormal situations like failed passwords, that yes.

**Comment by bews** [comment]
> login, password change

Not sure about this. Definitely not in the current event -> cmd implementation.


> Shouldn't we be emitting auth logs like other tools (ssh, etc.) and then monitoring

Logs will add more steps before any action + daemon is needed:
```
event
  ↓
logs
  ↑
daemon
  ↓
action
```
Current scheme:
```
event
  ↓
action
```
If you really need logs, then use this cmd to generate them in any format you want.

Current way has more flexibility, so I do not think limiting output to logs only is a good idea. For example, this feature can be used to report strange activity to slack/discord/gitter/ifttt and get notifications right away (without any daemons).

**Comment by xPaw** [comment]
I think base code should have logging, but not this. This is better suited as a plugin (whenever we get these!).

**Comment by astorije** [comment]
Fully agreed with @xPaw.
Most software I know use that logging mechanism, including Nginx and sshd. I am not aware of mechanisms where these 2 would run arbitrary commands.

Closing for reasons detailed above. We can reopen this if other @thelounge/maintainers feel strongly about the opposite.

**Pull request closed without merging**
