### PR TITLE
Use require() instead of import in client code

### LINKED ISSUE #895: Use require() instead of import
Ref: #853

### PR DESCRIPTION
**Pull request by xPaw**
Closes #895.

Got bitten by `Block-scoped declarations (let, const, function, class) not yet supported outside strict mode` while working on #972 and to get strict mode gotta drop `sourceType` in eslint.

### CODE REVIEW

**Comment by Bonuspunkt** [comment]
just to keep in mind
Tree-shaking should perform better when used with import (ES-modules)
http://2ality.com/2015/12/webpack-tree-shaking.html

**Comment by xPaw** [comment]
@Bonuspunkt Don't think that's a problem in our case.

**Comment by xPaw** [comment]
It's due to node4 support.

**Comment by astorije** [comment]
> It's due to node4 support.

These are all client-related though so that shouldn't matter.
This is probably a problem of configuration, but when it comes to CI, we should have:

- Node 4, 6, 7, etc. run against our server tests
- Browser(s) or Phantom or whatever run against our client tests

I remember @Bonuspunkt brought up this issue some time ago and there is probably a good way (or several) to address it.
Maybe something like [this](http://engineering.widen.com/blog/testing-future-web-stack/) could bring an element of solution?

**Comment by xPaw** [comment]
It matters if we test client code, which we do for the message parser.

**Comment by astorije** [comment]
Right, I agree, but yeah we should run client tests against a browser, not against Node (or at least disable client tests on Node v4, but probably not the path we want to take :S).

**Comment by astorije** [comment]
This also closes #974.

**Comment by xPaw** [comment]
:+1:

**Pull request merged**
