### PR TITLE
command-line/add,reset: reword password prompt

### PR DESCRIPTION
**Pull request by williamboman**
This makes the password prompts not look like a root access password prompt.

### CODE REVIEW

**Comment by YaManicKill** [comment]
Interesting. Should we make it even more obvious by saying something like "Enter TheLounge password"?

**Comment by williamboman** [comment]
> Interesting. Should we make it even more obvious by saying something like "Enter The Lounge password"?

I think `The Lounge password` is a bit dubious, something like `Enter new user's password: ` perhaps?

**Comment by maxpoulin64** [comment]
I'm really not a fan of super long prompts. Maybe `New password:` would be enough to clear the confusion with the root password? Or maybe we could go the sudo way, `[sudo] Password for max-p:` and write something like `[lounge] New password:`?

In general I think it shouldn't be our problem that the user can confuse prompts from other programs they use with The Lounge. If you use `su -c` you should be aware that `su` has a `Password:` prompt before ours.

**Comment by williamboman** [comment]
> and write something like [lounge] New password:

:+1:, I like it!

**Comment by maxpoulin64** [comment]
Fine by me :+1:

**Comment by YaManicKill** [comment]
Yes, I like this. However, as @astorije would probably say, it should probably be [thelounge] as that's our shortened version of the name.

**Pull request merged**
