### PR TITLE
Autoload more history on scrolling

### PR DESCRIPTION
**Pull request by bews**
Works the same way as on Discord.

Related: #1131, #207, #1038

- [x] Find the way to fix scroll bugs

### CODE REVIEW

**Comment by YaManicKill** [comment]
How well does this work? Is it nice and smooth? The code looks really simple, but I'm just a little suspicious about it being so small and simple because @astorije tried this and had some bugs. I've not looked into how he did it, though.

**Comment by bews** [comment]
> How well does this work? Is it nice and smooth?

Yep, I didn't notice any problems.

> I'm just a little suspicious about it being so small and simple because @astorije tried this and had some bugs.

This PR doesn't have any of that bugs:
- #1045 fixed multiple load
- "Show more" button is still here + message count check was added, so /clear works
- `.off("scroll")` was added to fix multiple event listeners

**Comment by bews** [comment]
Wait, found some bugs on mobile.

**Comment by bews** [comment]
Finally fixed scroll bugs :weary:

**Comment by xPaw** [comment]
We've ran into same problem with restoring scroll position when more history is loaded. Your solution is going to be a problem if `more` does not arrive instantly (e.g. slow mobile network), and will produce an unwanted jump (e.g. scroll up and down quickly).

You can see my code here https://github.com/thelounge/lounge/compare/xpaw/infinite-scroll
It uses IntersectionObserver to not deal with scroll position and counting how many messages there are.

**Comment by bews** [comment]
In my instance `more` never arrive instantly (because of CF and PI) and I haven't noticed this before. Is this really an issue?

Anyway, I believe this can be easy fixed by updating scroll position in `more` event.

**Comment by xPaw** [comment]
It should be noticeable on a slow network (think second delay)

**Comment by bews** [comment]
> It should be noticeable on a slow network (think second delay)

I have 2-3 seconds delay here and noticed this only after you mentioned it. Maybe it's because I usually don't scroll much while `more` is loading.

**Comment by bews** [comment]
Wait... I already have this in `more` event, maybe this is the reason I don't see any bugs.

**Comment by xPaw** [comment]
Try triggering the load event and scroll down quickly (e.g. page up then page down), I'd be surprised if that didn't jump you back after more messages loaded.

**Comment by bews** [comment]
> I'd be surprised if that didn't jump you back after more messages loaded.

Be surprised :rofl: 

Also, why are you trying to reimplement the same feature instead of just merging this?

**Comment by xPaw** [comment]
Using proper API for this is better than it checking scroll and counting messages.

**Comment by bews** [comment]
Well, you can't fix this unless you start checking scroll :laughing: So you'll have a proper API with a scroll check :smiley:

**Comment by xPaw** [comment]
I tested this PR, it definitely has it's own issues. Doing a pageup triggers it multiple times and it even gets visibly glitchy. There's a bit unrelated issue where position does not reset correctly when more messages get appended (this bug existed before).

I have fixed the scroll reset in my branch by using `requestAnimationFrame` by the way.

**Comment by bews** [comment]
> Doing a pageup triggers it multiple times and it even gets visibly glitchy.

Wat, it absolutely can't get triggered multiple times, look at the code. I also tested this to be sure. It may be some other bug with pageup (which is already fixed on master IIRC).

**Comment by xPaw** [comment]
> Wat, it absolutely can't get triggered multiple times, look at the code.

I tested whatever you currently had in the current state, and it absolutely did produce glitchy UI.

**Comment by bews** [comment]
I definitely don't have such problem on my instance, so it isn't related to this PR. I'll test current branch again tomorrow.

**Comment by bews** [comment]
Turned out you were right: it triggers multiple times (but only on good connection, so I don't have this on my instance). The reason for this was pageup animation, fixed it.

**Comment by MaxLeiter** [comment]
Tests not passing

**Comment by bews** [comment]
It's because of conflicts. I'll fix them if we agree to merge this instead of #1318.

**Comment by xPaw** [comment]
> Turned out you were right: it triggers multiple times (but only on good connection, so I don't have this on my instance).

And this is precisely why you need to be calm instead of telling me to "look at the code".

**Comment by bews** [comment]
> And this is precisely why you need to be calm instead of telling me to "look at the code".

Yeah, but I still agreed to test it again. It's just hard to believe that tested for months code can have such obvious bugs.

**Comment by MaxLeiter** [comment]
I haven't tested this, but I'd rather this over #1318 due to more widespread browser support. No reason to use a brand new API

**Comment by xPaw** [comment]
> No reason to use a brand new API

The reason would be that new API is completely asynchronous, so it's a performance win.

**Comment by xPaw** [comment]
Didn't mean to close this, damn github ui.

**Comment by astorije** [comment]
I also very much prefer #1318 over this PR for the fact that it leverages native browser interaction, and is properly async. This only applies if we ship the polyfill the spec authors came up with though.
And when it comes to API change... well, let's hope there won't be too many breaking changes 😅

Thanks for your help, @bews!

**Comment by astorije** [comment]
#1318 being in good shape to be merged (upon the official polyfill being fixed), it all seems like we will go for the browser-native solution instead. Thanks for triggering work on this, @bews!

**Pull request closed without merging**
