### PR TITLE
Create a single function to render networks to reduce code duplication

### PR DESCRIPTION
**Pull request by xPaw**
Fixes a bug @maxpoulin64 found: https://github.com/thelounge/lounge/pull/332#issuecomment-230071951

### CODE REVIEW

**Comment by astorije** [comment]
With all the recent changes, I'll rebase this on master and test this before merging.

**Comment by maxpoulin64** [comment]
ooooo, I was sure I had reviewed that one. I'll review as well, although it's liekly fine (it's a different section and really just removes duplicated code)

**Comment by astorije** [comment]
@maxpoulin64, I just rebased this PR with master, feel free to test it, I'll test when I can find some more time later.

**Comment by maxpoulin64** [comment]
Yeah, 👍  for me. Works fine, and it's a pretty simple change.

**Comment by astorije** [comment]
Cool, 👍 and merging.

**Pull request merged**
