### PR TITLE
Fix unhandled message color in Crypto theme

### PR DESCRIPTION
**Pull request by MaxLeiter**
| Before                            | After                            |
|-----------------------------------|----------------------------------|
| before | after |

### CODE REVIEW

**Comment by astorije** [comment]
This is inherited from [here](https://github.com/thelounge/lounge/blob/4541309988c5fee292eeaf41c76d9bbdc899e1c7/client/css/style.css#L952-L954) and I believe it's on purpose that unhandled numerics are being dimmed out.
But I'm actually curious, what made you feel this needed fixing?

**Comment by MaxLeiter** [comment]
At first I was unable to see the numbers, then realized they were there, just incredibly dim. Felt sloppy/unintentional to me for them to be "kind of" visible.

**Comment by astorije** [comment]
Right, but note that this is true for the default theme as well, which I think needs fixing too.
What do you say we instead:

- Put same color than the timestamp for both Example (we really need a name lol, once we derive from the Shout color!) and Crypto
- Move that design element from `style.css` to `example.css` to make themes independent from default stylesheet, in the continuity of #615 and #359 ?
- Make sure Morning and Zenburn are still OK

**Comment by MaxLeiter** [comment]
Done, @astorije. Both morning and zenburn already handle unhandled messages:

[Morning](https://github.com/thelounge/lounge/blob/master/client/themes/morning.css#L187) and [Zenburn](https://github.com/thelounge/lounge/blob/master/client/themes/zenburn.css#L213)

**Comment by xPaw** [comment]
Could this be a muted color, not completely black? It's slightly confusing as it might seem like a normal nickname, maybe we need to add an icon before the numeric?

**Comment by astorije** [comment]
@MaxLeiter, could you make it `#ddd` [like `#chat .time`](https://github.com/thelounge/lounge/pull/653/files#diff-97db1f70168fb5f12457b238ff6052b5L827)?

**Comment by MaxLeiter** [comment]
Done

**Pull request merged**
