### PR TITLE
Add support for banlist messages

### LINKED ISSUE #1008: Add support for banlist messages
We ignore banlist messages which means we can't view them. Ideally a GUI would be nice eventually, but we should at least support seeing the messages.

### PR DESCRIPTION
**Pull request by YaManicKill**
Fixes #1008

### CODE REVIEW

**Comment by MaxLeiter** [comment]
is it common to push to lobby? not to the channel the command is being called?

**Comment by xPaw** [comment]
Could use the special Chan type, same as /list.

**Comment by YaManicKill** [comment]
> is it common to push to lobby? not to the channel the command is being called?

In my experience, most IRC clients only push to the channel if it is a message directly.

I mean, ideally we would want to show a modal or something, with buttons to remove from the banlist, but this is just a first version so that we support it **at all**.

> Could use the special Chan type, same as /list.

I guess we could, yeah.

I think the thing is we don't want to end up just everything being a channel, because then we will end up not doing it in a nicer way, as we are a web app and we want to do things nicely for the user, not just in the simplest way possible.

But if you think that's the best thing to do for this first version, then I'm happy to do that.

**Comment by YaManicKill** [comment]
Well, I've pushed a commit to have a special chan for banlist entries. I'm not using any special message format (like the chanlist is). It's probably best if I do, and I pass the other information through to the client for showing.

For reference, this is what we get back from the server:

```
[ { channel: '#channelthatdoesntexist',
    banned: 'test!*@*',
    banned_by: 'ymk2!~ymk2@29.93.2.81.in-addr.arpa',
    banned_at: '1491320726' } ]
```

So it's probably worth showing the banned by and the banned at. I'll add that. See what you think about this.

**Comment by astorije** [comment]
@YaManicKill, mind adding an entry in the "commands" section of the help window, between `/back` and `/ctcp`?

**Comment by YaManicKill** [comment]
Alright, I have completely changed this.

Now it is a custom chan with custom messages, basically the same as how `/list` works, but obviously showing useful information for the banlist.

`/banlist` also wasn't a command we supported, so I added that so people don't have to remember the correct mode.

I have also added `/banlist` to the help section, as requested.

It works quite nicely now, I think.

**Comment by YaManicKill** [comment]
>Mind rebasing on master to take into account the recent changes to special channels by #1018?

Yeah, I'll do that soon.

**Comment by YaManicKill** [comment]
Rebased onto master, and using the new stuff from #1018.

**Comment by astorije** [comment]
@YaManicKill just so you know I didn't make any changes but when I wanted to test I got that `undefined` bug back so I rebased with `master` to be able to test then figured I might as well send that up-to-date version.

**Comment by YaManicKill** [comment]
Alright, I have added the command to the autocompletion list, and I have rebased and squashed. I think this is good to go now, then,

**Pull request merged**
