### PR TITLE
Different way to display highlights

### PR DESCRIPTION
**Pull request by xPaw**
I've been using this on my instance for a while, and it's way better than changing the text color to red.

### CODE REVIEW

**Comment by YaManicKill** [comment]
I have been using your css for this for quite a while, and I love it. It makes highlights a lot easier to notice. :+1:

**Comment by YaManicKill** [comment]
(I won't merge in yet though, I think this needs at least 1 more)

**Comment by MaxLeiter** [comment]
Been using the CSS for a while, definitely support changing :+1:

**Comment by maxpoulin64** [comment]
I like it, but it looks kind of meh on mobile however: 
screenshot_2016-07-02-21-15-16

Maybe keep the current behavior in the media queries for small screens?

**Comment by astorije** [comment]
I understand the technical need (not changing the color of the text itself) and the practical need (easily identifying notices when scrolling back). From a UI/design perspective, this severely contradicts with the rest of the application, whether it's the color itself or the fact that we foreground-color, etc. It is also visually very aggressive (again, I get the need to distinguish these).

Are you guys open to discussing something more in line with the global design and less aggressive to the eye? A lot of things are possible here, I believe, and I could share ideas if there is interest.

**Comment by xPaw** [comment]
@maxpoulin64 I like it on mobile too, using red text is kind of crap to quickly find the highlights.

@astorije Aggressive styling works quite well for highlights, especially in busy channels. I specifically didn't change the background on messages to not be even more aggressive (and to avoid styling issues). Please do share your ideas if you have any.

**Comment by YaManicKill** [comment]
I'm happy with either this being merged or not. I care less about these styling changes because I can just change them locally now :-P

Maybe it's worth leaving the default and having this as 1 of the first plugins, seeing as it looks like we might actually have a plugin system soon (yay). Because this is definitely a case of personal preference, and you are never going to make everyone happy.

**Comment by maxpoulin64** [comment]
Given the current state of the opinions, I think we should make this a custom CSS entry instead, or at least an option. I actually like the dark variants of this, but I for the default white theme I think it looks kinda bad.

Could we maybe have it only for morning and zenburn? I'm under the impression that the people using those themes are also the people that tends to want the bright highlights. Sounds like a good compromise for the meantime?

**Comment by YaManicKill** [comment]
Is it worth closing this if it isn't going to go anywhere?

**Comment by xPaw** [comment]
@YaManicKill I still want to get better highlights. Need to hear what @astorije has in mind.

**Comment by YaManicKill** [comment]
Nudge. @astorije you had any thoughts?

**Comment by bews** [comment]
Interesting idea, I thought about it myself after seeing something like this in discord. 
The problem is I like when my messages are highlighted too, which will be not so good with this design (assuming these 2 highlights will use the same design, as they should).

So for now I use underline highlighting:


It looks good on mobile too.

**Comment by xPaw** [comment]
https://github.com/thelounge/lounge-theme-solarized has this. Since this PR is not moving anywhere I will close it.

**Comment by xPaw** [comment]
@thelounge/maintainers I think this needs to be given a chance again now that nicknames are colored in messages. I've already heard it's harder to scan for highlights because some nick colors are also red.

**Comment by astorije** [comment]
> I've already heard it's harder to scan for highlights because some nick colors are also red.

Agreed.

I am not a fan of the original solution, it does feel like a bandaid to replace the broken current situation, but I didn't get a chance to play with something better.
I was thinking having up/down arrows to move across highlights would be very useful. That would make it for easy browsing of recent highlights.
@xPaw, what about something like the following:

screen shot 2017-12-04 at 18 37 58

It obviously needs UI tweaking, but as an idea.
Yes, it's more discreet than your solution, but I think way more eye-catchy when scrolling than the current solution we have and would be nice with other mechanisms like being able to browse across highlights.

**Comment by xPaw** [comment]
@astorije That's not the worst thing, anything is better than just setting the color to red.

**Pull request closed without merging**
