### PR TITLE
Expand user model

### PR DESCRIPTION
**Pull request by zchrykng**
Captures more data in the User model. Is needed for other features I am working on. Such as automatically banning using accounts when the server supports it.

### CODE REVIEW

**Comment by MaxLeiter** [comment]
Providing this data to the client (maybe not for this PR) will allow functionality like #356

**Comment by YaManicKill** [comment]
I'm quite a strong proponent of only putting code in when we actually need it. Why would we merge this in without anything actually using that code? I'd suggest leaving it until something actually needs that. Having extra data lying around when we don't need it feels a little unnecessary.

**Comment by astorije** [comment]
I'm with @YaManicKill on that one. Unused code is dead code, and since it's unused (and untested), it's likely that one of us will break it silently. Then good luck fixing that 😅

@zchrykng, maybe you could instead build on your branch/commits, adding your feature there, and when you're done, the whole PR would make more sense?

**Comment by xPaw** [comment]
I agree with both. Going to close this for now.

**Comment by zchrykng** [comment]
Yep makes sense. When I have time to finish it I will do a pull request for the finished feature.

**Pull request closed without merging**
