### PR TITLE
Reactify

### PR DESCRIPTION
**Pull request by yofreke**
## Do not merge

I have been watching this project for a bit, and love the look and feel.  My day job is writing web apps, and thought I might lend a hand in updating the project to use some more modern tech.
### Getting started

``` bash
npm run serve
# If you want the server as well
npm run start
```

Just the client: http://localhost:8080/

Client with params: http://localhost:8080/?wsURL=localhost:9000&debug=lounge:*

### CODE REVIEW

**Comment by nornagon** [comment]
Hey, also check out https://github.com/nornagon/lounge/tree/react-sidebar -- I've been doing significant work on this. Would be happy to chat on IRC about it :) you in freenode/#thelounge?

**Comment by yofreke** [comment]
I gotta run right now, but I should be around tomorrow some.  I can hop on IRC then.

**Comment by fbm-static** [comment]
How's it going? Can this be updated? Ther appears to be alot of conflicts when merged from the latest commit on master.

**Comment by yofreke** [comment]
Hey!  Things picked up in a major way around work for me.  I'm hoping to pick this up again at some point, but until then feel free to pick at the interesting parts (if there are any).

**Comment by xPaw** [comment]
Imo, at the moment moving to a different framework like this requires insane amount of work and blocks all the other work (can't work on other PRs because this one effects majority of the code), so I'm not sure it's worth the effort, at least now.

**Comment by fbm-static** [comment]
Maybe for a new major version. Ofcouse there's the argument of which one to use, vue.js comes to mind.

**Comment by xPaw** [comment]
I would focus our work on other stuff at the moment.

**Comment by astorije** [comment]
I tend to think that if the community is willing to help us with that, then that's great. @xPaw, I totally agree that there are other points to focus on, but if contributors are willing to make this evolve in order to follow what's being worked on right now, that's just great.

Anyway, KUTGW, I do appreciate it a lot :)

**Comment by YaManicKill** [comment]
Right, so my question is ... what advantages would this actually give us? We don't always need to add a JS framework to everything. It's quite nice working on something that is pretty close to pure JS..

Obviously, appreciate the effort, @yofreke but I just don't see why we would need to do this. Don't get me wrong, I appreciate frameworks, and I use angular and some others on many projects, but I don't see what it would give us because we have a working application that just needs work done to it.

**Comment by xPaw** [comment]
@thelounge/maintainers close this and the other react PR then?

**Comment by YaManicKill** [comment]
> close this and the other react PR then?

Unless anyone can give me a benefit of doing this, yes.

**Comment by xPaw** [comment]
By the way, this discussion also applies to #610, as we have two React PRs.

**Comment by YaManicKill** [comment]
Yeah, I have the same opinion with that.

**Pull request closed without merging**
