### PR TITLE
Format messages on copy

### LINKED ISSUE #1146: Copying text has new lines between time, username, and message
I think this is due to the new layout in chat.

When you copy something like:

```
09:54 YaManicKill test
```

What you get copied into your clipboard is:

```
09:54
YaManicKill
test
```

This is probably due to the new flexbox layout. Not sure of the best way to do it, we could intercept the copy and remove some of the new lines, but that feels...not great. But I can't think of a better way to do it.

I feel like this should be a blocker for 2.3.0, but if we don't have an idea for a fix this week, maybe not.

### PR DESCRIPTION
**Pull request by xPaw**
Fixes #1146.
Removes whitespaces.
Adds < > around nickname.

Code mostly from #1232 but adds more checks.

### CODE REVIEW

**Comment by astorije** [comment]
On server window, this does:

```
12:40 <> -
12:40 <> -
12:40 <> - By connecting to freenode you indicate that you have read and
12:40 <> - agree with our policies and guidelines as published on
12:40 <> - https://freenode.net
```

Maybe no `<>` if nick is empty? I don't know, just a thought. I just want to make sure we know the edge cases.

Also:

```
12:41 <ChanServ> [#freenode] Our freenode #live conference takes place Oct 28 and 29, we would love to see you there! See https://freenode.live/conference/fn-live17 for details.
```

This is actually a notice. Again, it's fine by me as it is, but reporting here just in case.

**Comment by xPaw** [comment]
@astorije Ah, that's why there was a length check on the name...

**Comment by astorije** [comment]
Ahah, when joining a channel, copying and pasting the first 3 lines that appear ("<self> joined" + "topic is: ..." + "topic was set by..."):

```
12:43 <> 
12:43 <> 
12:43 <> 
```

**Comment by astorije** [comment]
Copying:

screen shot 2017-08-26 at 12 46 04

Pasting:

```
 <> nk you!
12:45 <n1174> sepi
12:45 <@emerson> You're welcome!
```

See extra `<>`

**Comment by astorije** [comment]
Wow lol. Copying:

screen shot 2017-08-26 at 12 47 18

Pasting:

```
12:45 <@emerson> You're welcome!
12:45 <> 
12:45 <religiono> emerson: can I too get a cloak
12:45
		12:45
	
		12:45 <> 
12:45 <> 
12:45 <> 
12:45 <sandiego> last time i was in here, i asked to cloak my nickname, for any reason it still isnt :(
12:46 <Mewloman> hello
```

**Comment by xPaw** [comment]
@astorije I fixed whitespace trash.

**Comment by astorije** [comment]
Fixed linting issues and rebased on `master` because why not :)

**Comment by astorije** [comment]
Not sure how we should handle partially selected nicks:

Copying:

screen shot 2017-08-26 at 18 20 21

Pasting:

```
 <0x51> https://youtu.be/qRz77mkY46g Kamilion
```

**Comment by astorije** [comment]
Copying previews:

screen shot 2017-08-26 at 18 25 18

Pasting:

```
18:19 <amd_0x51> https://youtu.be/qRz77mkY46g Kamilion      Satellite Hacking For Fun And Profit (Blackhat 2009) Full Video Details: http://www.securitytube.net/video/263
```

Any chance those could be in different lines instead of one?
It would be annoying if you had to handle all cases one by one, is it possible to reformat `from` only (or so), and leave the rest as is? Or would that also be a problem?

**Comment by astorije** [comment]
So regarding condensed/not-condensed status messages, copying these:

Condensed | Expanded
--- | ---
screen shot 2017-08-26 at 18 28 13
screen shot 2017-08-26 at 18 28 38

Both result in the following paste:

```
18:26 <LinuxDude> For my own reference
18:26 		18:26 	 		18:26 1 user has left the channel, and 1 user has changed nick  Sousa|Overwatch is now known as Sousapro CrazyWar (68cf8ed2@gateway/web/cgi-irc/kiwiirc.com/ip.104.207.142.210) has left the channel 	(#freenode)
18:26 Sousa|Overwatch is now known as Sousapro
18:26 CrazyWar (68cf8ed2@gateway/web/cgi-irc/kiwiirc.com/ip.104.207.142.210) has left the channel 	(#freenode)
18:26 <amd_0x51> you encrypt them?
```

- How come all status messages get copied? Shouldn't they be ignored since they are in `display: none`?
- With native copying, the hidden time on condensed message is not selected thanks to `    visibility: hidden;`, they seem to be selected/copied again now
- Time gets pasted 3 times lol.

Hang in there, we're getting close :)
It's already pretty cool as it is, just studying edge cases to find bugs!

**Comment by dgw** [comment]
Are previews meant to be copied at all? That seems like part of the UI, rather than part of the content.

**Comment by astorije** [comment]
Right, but if I select them, I expect to have them in the clipboard when copying them. And on the other hand, it would be kind of a shame to make them not selectable at all.

**Comment by starquake** [comment]
Have you seen how I choose what gets copied to the clipboard in #1232? I thought the idea of selecting what gets copied by adding classes in the template was quite neat. In a way, the clipboard is just another representation of the same text. I'll fiddle around some more with my solution to see if it could still be viable as an alternative solution.

**Comment by xPaw** [comment]
I have changed the code to copy messages into an invisible element in the DOM and remove flex with CSS.

**Comment by astorije** [comment]
Hey hey, this is working really well!

I'm going to continue posting oddities I find here, but at that point I think we should call it a go and address those later, unless they are big issues.

---

Copying:

screen shot 2017-08-30 at 21 08 25

Pasting:

```
#astorije 
21:07
astorije2
test
21:07
astorije
test
```

**Comment by astorije** [comment]
When copying:

screen shot 2017-08-30 at 21 11 17

I paste:

```
21:09 <Egyptian> pls help me with the simple code. i need a 2nd set of eyes
````

But when copying:

screen shot 2017-08-30 at 21 11 25

I paste:

```
21:06 Topic set by jimi|ansible on 1 August 2017, 21:31:37
21:09 <Egyptian>  pls help me with the simple code. i need a 2nd set of eyes
```

Note the 2 whitespaces between nick and text in last paste (I told you they'd be nitpicks).

**Comment by astorije** [comment]
@xPaw, approved this so feel free to merge, but please rebase on `master` and play with it a bit before merging since #1475 got merged and might affect this. Maybe #1485 could affect it too?

**Comment by xPaw** [comment]
Yeah don't merge yet, it needs more testing.

**Comment by YaManicKill** [comment]
I think it's good to merge, personally. Not seen any issues and been running it for a few days.

**Pull request merged**
