### PR TITLE
Make sure self messages are never highlighted

### LINKED ISSUE #156: Self mentions should not trigger highlights
Example:

screen shot 2016-03-07 at 01 02 02

### PR DESCRIPTION
**Pull request by astorije**
Fixes #156.

### CODE REVIEW

**Comment by dgw** [comment]
I was thinking about this yesterday and didn't get around to making an issue for it, and here's a PR all set to fix it. :+1:

**Comment by astorije** [comment]
This is a quick fix, but maybe a wee bit longer-term solution should be to parse and trigger on the client instead, like #152 is doing, no?

**Comment by maxpoulin64** [comment]
Wouldn't it be better to check for self before the loop and avoid splitting the message entirely instead of doing it and overriding it right after?

Also, my PR doesn't actually touch that. This function is only responsible of turning IRC messages into HTML. If we want to handle highlights on the client, it would fit more in the msg handler. One minor thing for client-side highlights: if the user changes nicks and reload the page, the previous highlights will no longer be highlighted. Storing it in the server object has the benefit of making it permanent.

**Comment by xPaw** [comment]
@maxpoulin64 is right, check for `self` and then avoiding message splitting would be a better way.

**Comment by YaManicKill** [comment]
Does this remove the need for #146 ?

**Comment by xPaw** [comment]
Hm, looks like yes, it does.

**Comment by YaManicKill** [comment]
Yeah, that's fine. I think it's better dealing with it this way, especially for this issue.

**Comment by astorije** [comment]
Good point guys, I'll fix that. Also, I have a decent (well, in my opinion :p) idea how to make these testable, will post here when I get to it.

**Comment by astorije** [comment]
Hi all, took your comments into consideration to make things nicer. Thanks for looking carefully and sorry for being reckless in the first place :p
So now, the highlight lookup is only done if this is not a message from `self`. Also, I added something else: using `some()`, I stop the lookup early when one of the words matches. @maxpoulin64, I specifically thought of your addition to performance matters while doing so :D

**Comment by maxpoulin64** [comment]
:+1:  looks all good to me

**Pull request merged**
