### PR TITLE
Remove Node 0.10 from Travis CI

### PR DESCRIPTION
**Pull request by astorije**
This is needed for #43 to pass the CI.

### CODE REVIEW

**Comment by xPaw** [comment]
:+1:

We probably should also drop 0.12 later on.

**Comment by astorije** [comment]
Yep, but not today  :-)

**Comment by astorije** [comment]
@JocelynDelalande, ok with this?

**Comment by JocelynDelalande** [comment]
:+1: (as there is almost no other test than linting for now).

**Pull request merged**
