### PR TITLE
Remove session token hash conversion

### LINKED ISSUE #1958: Remove token hash conversion in 3.0
https://github.com/thelounge/lounge/pull/1940#discussion_r160712202

### PR DESCRIPTION
**Pull request by xPaw**
Fixes #1958

### CODE REVIEW

**Comment by astorije** [comment]
Honestly, it's _just_ a re-login, it's no big deal... :man_shrugging:

**Comment by astorije** [comment]
I think we should go with it. It's very unlikely that someone went from a v2.6 history to latest master at this point, since that PR was merged long ago. And even if that's the case, they just have to login.

**Comment by McInkay** [comment]
No, my concerns were based on an incorrect assumption on my part. I didn't realise it was only a login.

**Comment by astorije** [comment]
Thanks @McInkay! 🙏

**Pull request merged**
