### PR TITLE
add dockerfiles

### PR DESCRIPTION
**Pull request by davibe**

### CODE REVIEW

**Comment by MaxLeiter** [comment]
In order to keep the repository as clean/organized as possible, a separate repo managed by @williamboman was created to host the dockerfiles: https://github.com/thelounge/docker-lounge

**Comment by astorije** [comment]
Hey @davibe! Thanks for your contribution.

However, please note that there is a dedicated repository for Docker that can be found at https://github.com/thelounge/docker-lounge. See the Docker build at https://hub.docker.com/r/thelounge/lounge/.

On top of that, note that our documentations have a section for it: https://thelounge.github.io/docs/deployment/docker.html

Finally, if there is anything you think we can improve to make this other repository, the build, or the documentation more discoverable or simply better, please share :-)
@williamboman, you might want to take a look here if there any answers!

**Comment by davibe** [comment]
Ok. I did not check much indeed.. Thank you for the very quick response.

**Comment by maxpoulin64** [comment]
> For what is worth I prefer having those two files inside the main repo.

I can totally understand that.  We had to split it out because we were on our way to have a Caddyfile, Dockerfile, Vagrantfile, Ansible, juju, chef and puppet build scripts and... yeah you get the point :P That's why we now have a repo for all of them, which all have an independant lifecycle than the project itself. That way, we also don't have to worry about changes to the app itself breaking the automation scripts as those should in theory pull in the specific release they are designed for. No surprises, better design overall ^^

**Comment by astorije** [comment]
@davibe, feel free to open PRs to suggest improvements on the [dedicated repo](https://github.com/thelounge/docker-lounge).

**Pull request closed without merging**
