### PR TITLE
Enfore array/object desctructuring with ESLint

### PR DESCRIPTION
**Pull request by astorije**
These changes were **not** done by autofix.

Do we want this? I think it makes for nicer code on the long-term, but initially there are some weirdnesses.

### CODE REVIEW

**Comment by McInkay** [comment]
I'm not sure I want want to enforce destructuring. It can be nicer in some cases, but can be confusing in others.

**Comment by creesch** [comment]
Wouldn't it be better to make this and issue and do a pull request for this after most of the current pull requests have been merged for 3.0 ? Seems like it will only cause a bunch of merge conflicts either on this end or current pull requests that are otherwise ready to go.

**Comment by creesch** [comment]
I have the same concern as with #2073, wouldn't it be better to make this and issue and do a pull request for this after most of the current pull requests have been merged for 3.0 ? Seems like it will only cause a bunch of merge conflicts either on this end or current pull requests that are otherwise ready to go.

**Comment by astorije** [comment]
Yeah, I'm not going to merge this because enforcing this doesn't make sense, as I could see while fixing stuff. But I want to go through the options today and see if something can be taken from it.

When enforced on a project, I've noticed the shape of the code evolves slightly, for the better, so it's less something to apply after the fact (it can't be auto-fixed, even) and more something to have in mind when starting a feature.

**Comment by astorije** [comment]
Meh.

**Pull request closed without merging**
