### PR TITLE
Keep original <title> name when changing the title

### PR DESCRIPTION
**Pull request by xPaw**
Changing `title` in `index.html` will no longer require modifying and recompiling the javascript.

### CODE REVIEW

**Comment by astorije** [comment]
What's the purpose of this change? I'm not sure I'm getting it.

**Comment by xPaw** [comment]
This will allow changing the app title via `<title>` tag in html as it won't reset back to `The Lounge` as soon as a channel name appears in the title.

**Comment by astorije** [comment]
So, if I understand correctly, it's for those who want to brand their instances with their own name, now they just have to change the `<title>` in `index.html` instead of that + in the JS file?

**Comment by YaManicKill** [comment]
> So, if I understand correctly, it's for those who want to brand their instances with their own name, now they just have to change the <title> in index.html instead of that + in the JS file?

Exactly, we had someone in the IRC confused when changing the title in index.html didn't actually change the title.

**Pull request merged**
