### PR TITLE
Fix font size in themes for new textarea

### LINKED ISSUE #530: Themes needs to be updated for the new textarea
Due to the structure changes some CSS overrides in the themes are no longer specific enough to theme the textarea. Right now this causes font-size and styles inconsistencies.

### PR DESCRIPTION
**Pull request by maxpoulin64**
Fixes #530

### CODE REVIEW

**Comment by astorije** [comment]
For the record, Before/After:

Before | After
--- | ---
screen shot 2016-07-31 at 18 14 50 | screen shot 2016-07-31 at 18 15 33

@vectr0n, could you give it a try, please? :-)
LGTM, but waiting for @vectr0n's approval before giving a +1.

**Comment by maxpoulin64** [comment]
It is already confirmed, I had him add it to his custom CSS. That's why I thought it was already fixed 😄

**Comment by vectr0n** [comment]
@astorije tested with @maxpoulin64 and it resolved the problem :smile:

**Comment by astorije** [comment]
Perfect, 👍 and merging.

**Pull request merged**
