### PR TITLE
Add a simplified way to invite a user in the current channel

### PR DESCRIPTION
**Pull request by astorije**
This relates to https://github.com/thelounge/lounge/pull/7#issuecomment-184598927.

### CODE REVIEW

**Comment by astorije** [comment]
Now that I think of it, I need to make sure that this is only possible in channels, not lobbies or private messages.
I'll give it another test and run tomorrow!

**Comment by astorije** [comment]
Indeed, I needed an extra check. @xPaw or any other reviewer, this is good to go, and I'll let the first reviewer decide if this needs an additional review.

**Comment by xPaw** [comment]
:+1: Next step is showing a message like "You invited xxx to #yyy" :)

**Comment by astorije** [comment]
Yep, but not in this PR, correct?
Also, do you want to merge this now or prefer a second review?

**Comment by xPaw** [comment]
Yes another pr is fine. Change is small enough not to warrant a second review.

**Pull request merged**
