### PR TITLE
Preload scripts as soon as possible

### PR DESCRIPTION
**Pull request by xPaw**
Starts downloading them as soon as possible, instead of waiting for the whole HTML file to load.

### CODE REVIEW

**Comment by astorije** [comment]
I see more and more pages/snippets that, instead of having the JS declarations just before `</body>` would put their `<script src=...>` back in the `<head>` block and mark the `script` tag with `async`. Would that achieve the same goal?

**Comment by xPaw** [comment]
Having multiple scripts with async may have issues due to execution order.

**Comment by astorije** [comment]
Fair enough.

**Comment by astorije** [comment]
Merging, minor.

**Pull request merged**
