### PR TITLE
Use our logger instead of console.{log,error} for LDAP logs

### PR DESCRIPTION
**Pull request by astorije**
Ping @thisisdarshan and @lindskogen, could you let us know if the LDAP part looks fine to you?
Note that when running a public instance *and* LDAP, the LDAP part is now ignored and a warning is shown instead of crashing the app. @maxpoulin64, does that seem sensible to you?

### CODE REVIEW

**Comment by maxpoulin64** [comment]
Actually we left those as `console.log` on purpose since they are not logging but command-line outputs. It's a bit like if `ls` added `[INFO]` on every line, a bit odd... :-1:

**Comment by astorije** [comment]
> Actually we left those as console.log on purpose

I couldn't find discussion about this on GitHub, maybe it was IRC. Should we get rid of https://github.com/thelounge/lounge/pull/552/files#diff-c634a78f476381115a1c873dc965554dR10 then?

Also, this is not the important part of the PR lol, what about the other changes?

**Comment by maxpoulin64** [comment]
Ah yes, remove that and the other part is definitely :+1: especially the throw. Confused the two PRs for a moment 😅

**Comment by astorije** [comment]
@maxpoulin64, removed the changes in `list`, we can take this later anyway, I think the LDAP stuff is more important and valid on its own. Your 👎 hurts my feelings 😂

**Comment by maxpoulin64** [comment]
Actually I -1'd to prevent a merge because I can't add labels on mobile 😶

**Comment by astorije** [comment]
I'm not too fond of crashing the app but that's definitely one option (the one currently, which would change by getting rid of the `throw`).

A third option is to assume mode is private when `ldap.enable` is `true`.

Thoughts?

**Comment by maxpoulin64** [comment]
Okay I'm just bad at communicating tonight. Meant, the other stuff is good changes, including the removal of the throw 😅

**Pull request merged**
