### PR TITLE
Provide exact version into `npm install` command

### PR DESCRIPTION
**Pull request by xPaw**
Should avoid dumb `package.json` and caching issues.

### CODE REVIEW

**Comment by xPaw** [comment]
@McInkay Yeah it's hardcoded to `latest` in `package-json`

**Comment by astorije** [comment]
@xPaw, should we do ```${packageName}@$latest``` here to make sure updating packaging works? I don't know, not sure.

**Comment by xPaw** [comment]
@astorije `json.version` *is* latest as returned by the NPM web api.

**Comment by astorije** [comment]
By latest, I did mean the keyword `latest` as a string, not a version number. Doesn't `json.version` returns the latest version number?

**Comment by xPaw** [comment]
Yeah I understood what you meant. `package-json` which we use [explicitly requests](https://github.com/sindresorhus/package-json/blob/2312d0437c16d7117d354ae76f640c5ac25fe0e0/index.js#L15) `latest` via HTTP already so we will get the exact latest version number, without having to rely on npm CLI to do it.

**Comment by astorije** [comment]
@xPaw, I'm still confused as to why we don't do `@latest` ourselves, instead of relying on what `package-json` does behind the scenes.

**Pull request merged**
