### PR TITLE
Update screenshot in README

### PR DESCRIPTION
**Pull request by MaxLeiter**
lounge-3

### CODE REVIEW

**Comment by MiniDigger** [comment]
any special reason? 
while its cool that you show the embed you are also missing some stuff the other screenshot shows, like the alter in the secret server, the new messages bar, the red favicon etc.

**Comment by MaxLeiter** [comment]
I don't think the red favicon and altered message bubble color are important to have here because they aren't very explicit in their meaning without using the client. Should have new message bar though.

**Comment by YaManicKill** [comment]
My only question: should we make it a 16:9 screenshot, rather than this (which is 16:6) as that's more likely to be what people will be viewing it at. This one seems a little squished on the y axis.

**Comment by MaxLeiter** [comment]
Thoughts on this as a new thumbnail for 2.5?

image

**Comment by astorije** [comment]
@MaxLeiter, :shipit:

**Pull request merged**
